version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: oz-tech-test-mongo
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
